routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DatabaseController;
use App\Http\Controllers\DataKeluargaController;
use App\Http\Controllers\DataLainController;
use App\Http\Controllers\DataPesertaDidikController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\InformasiController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PengumumanController;
use App\Http\Controllers\PesanController;
use App\Models\Pengumuman;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::middleware('auth')->group(function () {
    Route::get('/admin', [DashboardController::class, 'index']);
    Route::resource('/admin/informasi', InformasiController::class);
    Route::resource('/admin/pengumuman', PengumumanController::class);
    Route::get('/pendaftaran/{id}', [DashboardController::class, 'pendaftaran']);
    Route::post('/daftar_ulang/{id}', [DashboardController::class, 'daftar_ulang']);
    Route::get('/detil/{id}', [FormController::class, 'detil']);
    Route::get('admin/pesan_1', [PesanController::class, 'pesan_1']);
    Route::get('admin/pesan_1', [PesanController::class, 'pesan_1']);
    Route::post('pesan/update/{id}', [PesanController::class, 'update_pesan']);

    Route::get('sent_wa/{id}', [DashboardController::class,'sent_wa']);

    Route::get('export_data', [LaporanController::class,'export_data']);
});

Route::get('/', [FormController::class, 'index']);
Route::resource('/form', FormController::class);
Route::get('/cetak_form/{id}', [FormController::class, 'cetak_form']);
Route::get('informasi', [InformasiController::class, 'tampil']);
Route::get('pengumuman', [PengumumanController::class, 'tampil']);
Route::get('ada', [PesanController::class, 'ada']);



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Informasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Informasi extends Model
{
    use HasFactory;
}

app/Http/Controllers/InformasiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Informasi;
use Illuminate\Http\Request;

class InformasiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $informasi = Informasi::first();
        return view('informasi.index', compact('informasi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function show(Informasi $informasi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function edit(Informasi $informasi)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Informasi $informasi)
    {
        //
        $informasi->isi = $request->isi;
        $informasi->save();

        return back()->with('simpan', 'Data Berhasil Disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Informasi  $informasi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Informasi $informasi)
    {
        //
    }

    public function tampil(){
        $informasi = Informasi::first();
        return view('informasi.tampil', compact('informasi'));
    }
}

resources/views/informasi/index.blade.php
@extends('layouts.admin')
@section('content')
    	
	<section class="content-header">
	  <h1>
		Informasi Pendaftaran
		{{-- <small>Control panel</small> --}}
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Informasi Pendaftaran</li>
	  </ol>
	</section>

	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              {{-- <h3 class="box-title">Data Table With Full Features</h3> --}}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                {{-- <div class="pull-right box-tools"> --}}
                    <div class="box-body pad">
                        <form action="{{ route('informasi.update', $informasi->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <textarea required id="editor" name="isi" rows="10" cols="80">
                                {{ $informasi->isi }}
                            </textarea>
                            <br>
                            <button type="submit" class="btn btn-primary pull-left"><i class="fa fa-send"></i> Simpan</button>
                        </form>
                    </div>
              {{-- </div> --}}
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection
@section('js')
<script>

    CKEDITOR.replace('editor')
</script>
@endsection

resources/views/informasi/tampil.blade.php
@extends('layouts.siswa')
@section('content')
    	
	<section class="content-header">
	  <h1>
		Informasi Pendaftaran
		{{-- <small>Control panel</small> --}}
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Informasi Pendaftaran</li>
	  </ol>
	</section>

	<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              {{-- <h3 class="box-title">Data Table With Full Features</h3> --}}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="table-responsive">

                @if (isset($informasi))
                {!! $informasi->isi !!}
                @endif
              
              </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection