routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DatabaseController;
use App\Http\Controllers\DataKeluargaController;
use App\Http\Controllers\DataLainController;
use App\Http\Controllers\DataPesertaDidikController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\InformasiController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PengumumanController;
use App\Http\Controllers\PesanController;
use App\Models\Pengumuman;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::middleware('auth')->group(function () {
    Route::get('/admin', [DashboardController::class, 'index']);
    Route::resource('/admin/informasi', InformasiController::class);
    Route::resource('/admin/pengumuman', PengumumanController::class);
    Route::get('/pendaftaran/{id}', [DashboardController::class, 'pendaftaran']);
    Route::post('/daftar_ulang/{id}', [DashboardController::class, 'daftar_ulang']);
    Route::get('/detil/{id}', [FormController::class, 'detil']);
    Route::get('admin/pesan_1', [PesanController::class, 'pesan_1']);
    Route::get('admin/pesan_1', [PesanController::class, 'pesan_1']);
    Route::post('pesan/update/{id}', [PesanController::class, 'update_pesan']);

    Route::get('sent_wa/{id}', [DashboardController::class,'sent_wa']);

    Route::get('export_data', [LaporanController::class,'export_data']);
});

Route::get('/', [FormController::class, 'index']);
Route::resource('/form', FormController::class);
Route::get('/cetak_form/{id}', [FormController::class, 'cetak_form']);
Route::get('informasi', [InformasiController::class, 'tampil']);
Route::get('pengumuman', [PengumumanController::class, 'tampil']);
Route::get('ada', [PesanController::class, 'ada']);



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Pengumuman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengumuman extends Model
{
    use HasFactory;
}

app/Http/Controllers/PengumumanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pengumuman;
use Illuminate\Http\Request;

class PengumumanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data = Pengumuman::all();
        // dd($data);
        return view('pengumuman.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('pengumuman.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = new Pengumuman();
        $data->judul = $request->judul;
        $data->isi = $request->isi;
        $data->save();

        return redirect('admin/pengumuman')->with('simpan', 'Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function show(Pengumuman $pengumuman)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengumuman $pengumuman)
    {
        //
        return view('pengumuman.create', compact('pengumuman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pengumuman $pengumuman)
    {
        //
        $pengumuman->judul = $request->judul;
        $pengumuman->isi = $request->isi;
        $pengumuman->save();

        return redirect('admin/pengumuman')->with('simpan', 'Data Berhasil Disimpan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengumuman $pengumuman)
    {
        //
        $pengumuman->delete();
        return back()->with('simpan', 'Data berhasil Dihapus');
    }

    public function tampil(){
        $pengumuman = Pengumuman::all();
        return view('pengumuman.tampil', compact('pengumuman'));
    }
}

resources/views/pengumuman/create.blade.php
@extends('layouts.admin')
@section('content')

<section class="content-header">
    <h1>
        <i class='fa fa-users'></i> {{isset($pengumuman) ? 'Edit' : 'Tambah'}} Master Pengumuman &nbsp;&nbsp;
    </h1>

    <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Halaman Awal</a></li>
        <li class="active">Master Pengumuman</li>
    </ol>
</section>

<!-- Main content -->
<section id='content_section' class="content">
    
@if (isset($pengumuman))
<form class='form-horizontal' method='post' id="form" enctype="multipart/form-data" action="{{route('pengumuman.update', $pengumuman->id)}}">
@method('PATCH')
@else
<form class='form-horizontal' method='post' id="form" enctype="multipart/form-data" action="{{route('pengumuman.store')}}">
@endif
@csrf

<div class="panel panel-default" style="margin-bottom: 10px">
    <div class="panel-heading">
        {{-- <strong><i class='fa fa-users'></i> Tambah Master Pengumuman</strong> --}}
    </div>
    <div class="panel-body" style="padding:20px 0px 0px 0px">
        <div class="box-body" id="parent-form-area">

            <div class='form-group header-group-0'>
                <label class='control-label col-sm-2'> Judul <span class='text-danger' title='This field is required'>*</span></label>
                <div class="col-sm-10">
                    <input type='text' title="Pesan" required class='form-control' name="judul" id="" value='{{isset($pengumuman) ? $pengumuman->judul : old('judul')}}'/>
                    <div class="text-danger"></div>
                    <p class='help-block'></p>
                </div>
            </div>

            <div class='form-group header-group-0'>
                <label class='control-label col-sm-2'> Deskripsi <span class='text-danger' title='This field is required'>*</span></label>
                <div class="col-sm-10">
                    <textarea name="isi" class="form-control" id="editor" cols="30" rows="3">{{isset($pengumuman) ? $pengumuman->isi : old('isi')}}</textarea>
                    <div class="text-danger"></div>
                    <p class='help-block'></p>
                </div>
            </div>
            
        </div><!-- /.box-body -->
    </div>
</div>

<div class="row">
    <div class="col-sm-6"></div>
    <div class="col-sm-6">
        <div align="right">
            <input type="submit" name="submit" value='Simpan' class='btn btn-success'>
        </div>
    </div>
</div>

</form>
</div><!--END AUTO MARGIN-->

</section><!-- /.content -->
@endsection
@section('js')
<script>

	CKEDITOR.replace('editor')
</script>
@endsection

resources/views/pengumuman/index.blade.php
@extends('layouts.admin')
@section('content')
    	
	<section class="content-header">
	  <h1>
		Pengumuman
		{{-- <small>Control panel</small> --}}
        <a href="{{route('pengumuman.create')}}" id='' class="btn btn-sm btn-success" title="Tambah Data"><i class="fa fa-plus-circle"></i> Tambah Data</a>
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Pengumuman</li>
	  </ol>
	</section>

	<!-- Main content -->
    <section class="content">

      <div class='callout' style="margin: 0px; padding: 0px 30px 0px 15px;">
        @if (session('simpan'))
        <div class="row">
            <div class="alert alert-success alert-dismissible" role="alert">
                <h4 class="alert-heading">Berhasil!</h4>
                {{ session('simpan') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger alert-dismissible" role="alert">
                <h4 class="alert-heading">Gagal!</h4>
                @foreach ($errors->all() as $error)
                    <p>{{ $error }}</p>
                @endforeach
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
      </div>
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="box-header">
              {{-- <h3 class="box-title">Data Table With Full Features</h3> --}}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="" class="table table-bordered table-striped table-responsive">
                <thead>
                <tr>
                  <th>No</th>
                  <th>Judul</th>
                  <th>Isi</th>
                  <th>Created At</th>
                  <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
					@foreach ($data as $k=>$item)
					<tr>
						<td>{{ $k+1 }}</td>
						<td>{{ $item->judul }}</td>
						<td>{{ $item->isi }}</td>
						<td>{{ $item->created_at }}</td>
						<td>
              <form action="{{route('pengumuman.destroy', $item->id)}}" method="post">
                <a href="{{route('pengumuman.edit', $item->id)}}" class="btn btn-xs btn-success"><i class="fa fa-pencil"></i></a>
                @csrf
                @method('delete')
                {{-- <button type="button" class="btn_delete_modal_submit btn btn-xs btn-warning" data-toggle="modal" data-target="#deleteModal" data-url_modal="{{route('pengumuman.destroy', $item->id)}}"><i class="fa fa-trash"></i></button> --}}
                <button type="submit" class="btn btn-xs btn-warning"><i class="fa fa-trash"></i></button>
              </form>
						</td>
					</tr>
					@endforeach
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
@endsection

resources/views/pengumuman/tampil.blade.php
@extends('layouts.siswa')
@section('content')
<section class="content-header">
    <h1>
    Pengumuman
    </h1>
    <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Pengumuman</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <ul class="timeline">
            @foreach ($pengumuman as $item)
            <li>
                <i class="fa fa-envelope bg-blue"></i>
                <div class="timeline-item">
                <span class="time"><i class="fa fa-clock-o"></i> {{ $item->created_at }}</span>
                <h3 class="timeline-header">{{ $item->judul }} <small>By Admin</small> </h3> 
                <div class="timeline-body">
                {!! $item->isi !!}
                </div>
                </div>
            </li>
            @endforeach
            </ul>
        </div>
    </div>
</section>
@endsection