routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DatabaseController;
use App\Http\Controllers\DataKeluargaController;
use App\Http\Controllers\DataLainController;
use App\Http\Controllers\DataPesertaDidikController;
use App\Http\Controllers\FormController;
use App\Http\Controllers\InformasiController;
use App\Http\Controllers\LaporanController;
use App\Http\Controllers\PengumumanController;
use App\Http\Controllers\PesanController;
use App\Models\Pengumuman;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::middleware('auth')->group(function () {
    Route::get('/admin', [DashboardController::class, 'index']);
    Route::resource('/admin/informasi', InformasiController::class);
    Route::resource('/admin/pengumuman', PengumumanController::class);
    Route::get('/pendaftaran/{id}', [DashboardController::class, 'pendaftaran']);
    Route::post('/daftar_ulang/{id}', [DashboardController::class, 'daftar_ulang']);
    Route::get('/detil/{id}', [FormController::class, 'detil']);
    Route::get('admin/pesan_1', [PesanController::class, 'pesan_1']);
    Route::get('admin/pesan_1', [PesanController::class, 'pesan_1']);
    Route::post('pesan/update/{id}', [PesanController::class, 'update_pesan']);

    Route::get('sent_wa/{id}', [DashboardController::class,'sent_wa']);

    Route::get('export_data', [LaporanController::class,'export_data']);
});

Route::get('/', [FormController::class, 'index']);
Route::resource('/form', FormController::class);
Route::get('/cetak_form/{id}', [FormController::class, 'cetak_form']);
Route::get('informasi', [InformasiController::class, 'tampil']);
Route::get('pengumuman', [PengumumanController::class, 'tampil']);
Route::get('ada', [PesanController::class, 'ada']);



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use App\Models\DataKeluarga;
use App\Models\DataLain;
use App\Models\DataPesertaDidik;
use Illuminate\Http\Request;
use PDF;
use Illuminate\Support\Facades\DB;

class FormController extends Controller
{
    //
    public function index(){
        return view('form.form_index');
    }
    public function store(Request $request){
        // dd($request->all());
        // DB::beginTransaction();
        $data = DataPesertaDidik::where('nisn', $request->nisn)->get();
        if ($data->count() > 0) {
            $siswa = $data[0];
            return view('form.ada', compact('siswa'));
        }else{
            try {
                $siswa = new DataPesertaDidik();
                $siswa->nama_lengkap = $request->nama_lengkap;
                $siswa->jenis_kelamin = $request->jenis_kelamin;
                $siswa->nisn = $request->nisn;
                $siswa->nik = $request->nik;
                $siswa->nama_sekolah_asal = $request->nama_sekolah_asal;
                $siswa->alamat_sekolah_asal = $request->alamat_sekolah_asal;
                $siswa->tempat_lahir = $request->tempat_lahir;
                $siswa->tanggal_lahir = $request->tanggal_lahir;
                $siswa->agama = $request->agama;
                $siswa->provinsi = $request->provinsi;
                $siswa->kabupaten = $request->kabupaten;
                $siswa->kecamatan = $request->kecamatan;
                $siswa->kelurahan = $request->kelurahan;
                $siswa->alamat = $request->alamat;
                $siswa->transportasi = $request->transportasi;
                $siswa->no_hp = $request->no_hp;
                $siswa->jenis_bantuan = $request->jenis_bantuan;
                $siswa->no_bantuan = $request->no_bantuan;
                $siswa->lintang = $request->lintang;
                $siswa->bujur = $request->bujur;
                $siswa->save();
        
                $keluarga = new DataKeluarga();
                $keluarga->nama_ayah = $request->nama_ayah;
                $keluarga->pekerjaan_ayah = $request->pekerjaan_ayah;
                $keluarga->pendidikan_ayah = $request->pendidikan_ayah;
                $keluarga->penghasilan_ayah = $request->penghasilan_ayah;
                $keluarga->nama_ibu = $request->nama_ibu;
                $keluarga->pekerjaan_ibu = $request->pekerjaan_ibu;
                $keluarga->pendidikan_ibu = $request->pendidikan_ibu;
                $keluarga->penghasilan_ibu = $request->penghasilan_ibu;
                $keluarga->siswa_id = $siswa->id;
                $keluarga->save();
        
                $lain = new DataLain();
                $lain->nama_pondok = $request->nama_pondok;
                $lain->tinggi_badan = $request->tinggi_badan;
                $lain->berat_badan = $request->berat_badan;
                $lain->jarak_kesekolah = $request->jarak_kesekolah;
                $lain->waktu_kesekolah = $request->waktu_kesekolah;
                $lain->anak_ke = $request->anak_ke;
                $lain->jumlah_saudara = $request->jumlah_saudara;
                $lain->siswa_id = $siswa->id;
                $lain->save();
        
                $siswa = DataPesertaDidik::find($siswa->id);
                // dd($siswa);

                return view('form.ada', compact('siswa'));

                // $pdf = PDF::loadView('form.pdf', compact('siswa'));
                // return $pdf->stream($siswa->nama_lengkap.'-formulir-pendaftaran.pdf');
                // DB::commit();
            } catch (\Throwable $th) {
                // DB::rollBack();
                return back()->with('error', $th->getMessage());            
            }
            
        }
    }

    public function cetak_form($id){
        $siswa = DataPesertaDidik::find($id);
        $pdf = PDF::loadView('form.pdf', compact('siswa'));
        return $pdf->stream($siswa->nama_lengkap.'-formulir-pendaftaran.pdf');
    }

    public function detil($id){
        $siswa = DataPesertaDidik::find($id);
        return view('detil', compact('siswa'));
    }
}

resources/views/form/ada.blade.php
@extends('layouts.siswa')
@section('content')
<section class="content">
    {{-- <div class="callout callout-info">
        <h4>
            Formulir telah terkirim, silahkan cetak formulir <a href="{{ url('cetak_form', $data[0]->id) }}">Disini</a> 
            kemudian bawa ke sekolahan saat membayar pendaftaran
        </h4>
    </div> --}}

    <div class="row">
        <div class="col-md-6">
          <div class="box box-default">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>

              <h3 class="box-title">Informasi</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Formulir telah terkirim!</h4>
                Silahkan mengikuti prosedur pendaftaran berikut
              </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->

        <div class="col-md-6">
          <div class="box box-default">
            <div class="box-header with-border">
              <i class="fa fa-bullhorn"></i>

              <h3 class="box-title">Prosedur Pendaftaran</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              1. Download formulir pendaftaran di sini <a target="blank" href="{{ url('cetak_form') }}/{{ $siswa->id ?? '' }}" class="btn btn-success btn-sm"><i class="fa fa-download"></i> Download</a> <br>
              2. Tunjukan formulir tersebut kepada panitian PPDB SMP Futuhiyyah Mranggen <br>
              3. Membayar biaya pendaftaran <br>
              4. Pengumuman lolos seleksi akan diumumkan melalui no Wa yang terdaftar <br>
              5. Melengkapi berkas dan membayar biaya daftar ulang <br> <br>

              Contact Person : <br>
              Ibu Sa'adah <br>
              <a href="http://wa.me/6281238423174">wa.me/6281238423174</a>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>

</div>


</section>
@endsection

resources/views/form/data_keluarga.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Data Keluarga</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    {{-- <form role="form" action="{{ route('data_keluarga.store') }}"> --}}
        <div class="form-horizontal">
        <div class="box-body">
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Nama Ayah <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <input type="text" required class="form-control" name="nama_ayah" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Pekerjaan Ayah <span style="color: red">*</span> </label>
            <div class="col-sm-10">
            <input type="text" required class="form-control" name="pekerjaan_ayah" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Pendidikan Ayah <span style="color: red">*</span> </label>
            <div class="col-sm-10">
            <select name="pendidikan_ayah" required class="form-control" id="">
                <option value="">**Pilih Pendidikan</option>
                <option>Tidak Sekolah</option>
                <option>SD</option>
                <option>SLTP</option>
                <option>SLTA</option>
                <option>D3</option>
                <option>S1</option>
                <option>S2</option>
                <option>S3</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Penghasilam Ayah </label>
            <div class="col-sm-10">
            <select name="penghasilan_ayah" class="form-control" id="">
                <option value="">**Pilih Penghasilan</option>
                <option>Tidak Berpenghasilan</option>
                <option>< 500.000</option>
                <option>500.000 - 1.000.000</option>
                <option>1.000.000 - 3.000.000</option>
                <option>3.000.000 - 5.000.000</option>
                <option>> 5.000.000</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Nama Ibu <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <input type="text" required class="form-control" name="nama_ibu" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Pekerjaan Ibu <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <input type="text" required class="form-control" name="pekerjaan_ibu" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Pendidikan Ibu <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="pendidikan_ibu" required class="form-control" id="">
                <option value="">**Pilih Pendidikan</option>
                <option>Tidak Sekolah</option>
                <option>SD</option>
                <option>SLTP</option>
                <option>SLTA</option>
                <option>D3</option>
                <option>S1</option>
                <option>S2</option>
                <option>S3</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Penghasilam Ibu </label>
            <div class="col-sm-10">
            <select name="penghasilan_ibu" class="form-control" id="">
                <option value="">**Pilih Penghasilan</option>
                <option>Tidak Berpenghasilan</option>
                <option>< 500.000</option>
                <option>500.000 - 1.000.000</option>
                <option>1.000.000 - 3.000.000</option>
                <option>3.000.000 - 5.000.000</option>
                <option>> 5.000.000</option>
            </select>
            </div>
        </div>
        
        
        </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
        {{-- <button type="submit" class="btn btn-primary">Simpan</button> --}}
        </div>
    {{-- </form> --}}
</div>

resources/views/form/data_lain.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Data Lain</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    {{-- <form role="form" action="{{ route('data_keluarga.store') }}"> --}}
        <div class="form-horizontal">
        <div class="box-body">
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Rencana Pondok Pesantren</label> <br>
            <div class="col-sm-10">
                <input type="radio" name="pondok" value="ya" > Ya
                <input type="radio" name="pondok" value="tidak"> Tidak
                <select name="nama_pondok" class="nama_pondok form-control" id="">
                    <option value="">Pilih Pondok</option>
                    <option>Futuhiyyah</option>
                    <option>Al Mubarok</option>
                    <option>Darussa'adah</option>
                    <option>Al Badriyah</option>
                    <option>Al Amin</option>
                    <option>Nurul Burhani 1</option>
                    <option>Nurul Burhani 2</option>
                    <option>Darul Ma'wa</option>
                    <option>KH Murodi</option>
                    <option>Al Anwar</option>
                    <option>Al Imdad</option>
                    <option>Lainnya</option>
                </select>
                <div class="pondok_lain"></div>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Tinggi Badan (cm), Berat Badan (kg)</label>
            <div class="col-sm-10">
            <div class="form-inline">
                <input type="number" name="tinggi_badan" class="form-control" id="" placeholder="Tinggi Badan">
                <input type="number" name="berat_badan" class="form-control" id="" placeholder="Berat Badan">
            </div>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Jarak ke sekolah (km) </label>
            <div class="col-sm-10">
            <input type="number" class="form-control" name="jarak_kesekolah" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Waktu ke sekolah (menit) </label>
            <div class="col-sm-10">
            <input type="number" class="form-control" name="waktu_kesekolah" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Anak Ke, Jumlah Saudara <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <div class="form-inline">
                <input type="number" required name="anak_ke" class="form-control" id="" placeholder="Anak Ke">
                <input type="number" required name="jumlah_saudara" class="form-control" id="" placeholder="Jumlah Saudara">
            </div>
            </div>
        </div>

        </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
        {{-- <button type="submit" class="btn btn-primary pull-right"><i class="fa-send"></i> Kirim Formulir</button> --}}
        </div>
    {{-- </form> --}}
</div>

resources/views/form/data_peserta_didik.blade.php
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Data Peserta Didik</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    {{-- <form class="form-horizontal" action="{{ route('data_peserta_didik.store') }}"> --}}
        <div class="form-horizontal">
        <div class="box-body">
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Nama Lengkap <span style="color: red">*</span></label>
            <div class="col-sm-10">
                <input type="text" required class="form-control" name="nama_lengkap" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Jenis Kelamin <span style="color: red">*</span></label> <br>
            <div class="col-sm-10">
                <input type="radio" name="jenis_kelamin" value="L" checked> Laki-laki
                <input type="radio" name="jenis_kelamin" value="P"> Perempuan
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">NISN <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <input type="number" required name="nisn" class="panjang_nisn form-control" id="" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">NIK <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <input type="number" required name="nik" class="panjang_nik form-control" id="" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Nama Sekolah Asal <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <input type="text" required name="nama_sekolah_asal" class="form-control" id="" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Alamat Sekolah Asal <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <textarea required name="alamat_sekolah_asal" class="form-control" id="" cols="30" rows="3"></textarea>
            {{-- <input type="number" required name="alamat_sekolah_asal" class="form-control" id="" placeholder=""> --}}
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Tempat Lahir <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <div class="form-inline">
                <input type="text" required name="tempat_lahir" class="form-control" id="" placeholder="Tempat Lahir">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Tanggal Lahir <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <div class="form-inline">
                <input type="date" required name="tanggal_lahir" class="form-control" id="" placeholder="">
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Agama <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="agama" required class="form-control" id="">
                <option>Islam</option>
                <option>kristen</option>
                <option>Budha</option>
                <option>Khatolik</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Provinsi <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="" required id="provinsi" class="form-control select2">
                <option value="">Pilih Provinsi</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Kabupaten <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="" required id="kabupaten" class="form-control select2">
                <option value="">Pilih Kabupaten/Kota</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Kecamatan <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="" required id="kecamatan" class="form-control select2">
                <option value="">Pilih Kecamatan</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Kelurahan <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="kelurahan" required id="kelurahan" class="form-control select2_tags">
                <option value="">Pilih Kelurahan</option>
            </select>
            </div>
        </div>
        <div class="nama_lokasi"></div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Alamat <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <textarea name="alamat" required id="" cols="30" rows="3" class="form-control" placeholder="Isikan nama jalan / dusun / RT/RW "></textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Transportasi <span style="color: red">*</span></label>
            <div class="col-sm-10">
            <select name="transportasi" required class="form-control" id="">
                <option>Jalan Kaki</option>
                <option>Sepeda Motor</option>
                <option>Angkutan Umum</option>
            </select>
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">No WA <span style="color: red">*</span></label>
            <div class="col-sm-10">
                <input required type="text" name="no_hp" id="" class="form-control" placeholder="085123123123">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Jenis Bantuan</label>
            <div class="col-sm-10">
                <input type="checkbox" name="jenis_bantuan" value="KIP"> KIP
                <input type="checkbox" name="jenis_bantuan" value="KPS"> KPS
                <input type="checkbox" name="jenis_bantuan" value="BLT"> BLT
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">No Kartu Bantuan </label>
            <div class="col-sm-10">
            <input type="text" name="no_bantuan" class="form-control" id="" placeholder="">
            </div>
        </div>
        <div class="form-group">
            <label for="" class="col-sm-2 text-right">Lintang, Bujur </label>
            <div class="col-sm-10">
            <div class="form-inline">
                <input type="number" name="lintang" class="form-control" id="" placeholder="Lintang">
                <input type="number" name="bujur" class="form-control" id="" placeholder="Bujur">
            </div>
            </div>
        </div>

        </div>

        <div class="box-footer">
        {{-- <button type="submit" class="btn btn-primary pull-right">Simpan</button> --}}
        </div>
        </div>
    {{-- </form> --}}
</div>

resources/views/form/form_index.blade.php
@extends('layouts.siswa')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Formulir Pendaftaran Peserta Didik Baru
        {{-- <small>Preview</small> --}}
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Form</a></li>
        <li class="active">Formulir Pendaftaran Peserta Didik Baru</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      @if (Session::get('error'))
      <div class="row">
          <div class="alert alert-warning alert-dismissible" role="alert">
              <strong><i class="fa fa-info-circle"></i> {{ session('error') }}</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
      </div>
      @endif

      <div class="callout callout-info">
        <h4>Perhatian!</h4>
        1. Isikan formulir dengan benar dan lengkap <br>
        2. Bagian yang Bertanda <span style="color: red"><b> *</b></span> wajib diisi
      </div>
      <div class="row">
        <form action="{{ route('form.store') }}" method="post">
          @csrf
          
        <div class="data_nama"></div>
        <div class="col-md-12">
          @include('form.data_peserta_didik')
        </div>
        <div class="col-md-12">
          @include('form.data_keluarga')
          @include('form.data_lain')
        </div>
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-send"></i> Kirim Formulir</button>
      </div>
      </form>
    </section>
@endsection
@section('js')
<script>
  $.get("https://dev.farizdotid.com/api/daerahindonesia/provinsi", function(data){
      // console.log(data.provinsi);
      $.each(data.provinsi, function( key, value ){
        $('#provinsi').append("<option value='"+value.id+"'>"+value.nama+"</option>");
      });
  });
  
  $("#provinsi").change(function(){
    var id_provinsi = $(this).val()
    $.get("https://dev.farizdotid.com/api/daerahindonesia/provinsi/"+id_provinsi, function(data){
    $('.data_nama').append('<input type="hidden" name="provinsi" value="'+data.nama+'">')
    });
    $.get("https://dev.farizdotid.com/api/daerahindonesia/kota?id_provinsi="+id_provinsi, function(data){
      // console.log(data.kota_kabupaten);
      $('#kabupaten').html('')
      $('#kabupaten').append("<option value=''>Pilih Kabupaten</option>");
      $.each(data.kota_kabupaten, function( key, value ){
        $('#kabupaten').append("<option value='"+value.id+"'>"+value.nama+"</option>");
      });
    });
  })
  
  $("#kabupaten").change(function(){
    var id_kota = $(this).val()
    $.get("https://dev.farizdotid.com/api/daerahindonesia/kota/"+id_kota, function(data){
    $('.data_nama').append('<input type="hidden" name="kabupaten" value="'+data.nama+'">')
    });
    $.get("https://dev.farizdotid.com/api/daerahindonesia/kecamatan?id_kota="+id_kota, function(data){
      $('#kecamatan').html('')
      $('#kecamatan').append("<option value=''>Pilih Kecamatan</option>");
      $.each(data.kecamatan, function( key, value ){
      // console.log(value);
        $('#kecamatan').append("<option value='"+value.id+"'>"+value.nama+"</option>");
      });
    });
  })

  $("#kecamatan").change(function(){
    var id_kecamatan = $(this).val()
    $.get("https://dev.farizdotid.com/api/daerahindonesia/kecamatan/"+id_kecamatan, function(data){
    $('.data_nama').append('<input type="hidden" name="kecamatan" value="'+data.nama+'">')
    });
    $.get("https://dev.farizdotid.com/api/daerahindonesia/kelurahan?id_kecamatan="+id_kecamatan, function(data){
      $('#kelurahan').html('')
      $('#kelurahan').append("<option value=''>Pilih Kelurahan</option>");
      $.each(data.kelurahan, function( key, value ){
      // console.log(value);
        $('#kelurahan').append("<option value='"+value.id+"'>"+value.nama+"</option>");
      });
    });
  })

  $("#kelurahan").change(function(){
    var id_kelurahan = $(this).val()
    $.get("https://dev.farizdotid.com/api/daerahindonesia/kelurahan/"+id_kelurahan, function(data){
    // $('.data_nama').append('<input type="hidden" name="kelurahan" value="'+data.nama+'">')
    });
  })
  
  $('.nama_pondok').hide()

  $('input[type=radio][name=pondok]').change(function() {
    if (this.value == 'ya') {
      $('.nama_pondok').show()
    }else{
      $('.nama_pondok').hide()
      $('.pondok_lain').html('')
    }
  });
  
  $('.nama_pondok').change(function(){
    if($(this).val() == 'Lainnya'){
      $('.pondok_lain').append('<input type="text" name="nama_pondok" class="form-control" id="" placeholder="Ketikkan Nama Pondok">')
    }else{
      $('.pondok_lain').html('')
    }
  })

  $('.panjang_nik').change(function(){
    $val = $(this).val();
    if ($val.length != 16) {
        alert('Panjang NIK Harus 16 Digit');
        $(this).focus()
    }
  });

  $('.panjang_nisn').change(function(){
    $val = $(this).val();
    if ($val.length != 10) {
        alert('Panjang NISN Harus 10 Digit');
        $(this).focus()
    }
  });
</script>
@endsection